name: telescopecm-be

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: "telescopecm-be"
  LATEST: "latest"

jobs:
  Image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v3
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN_hazon }}
          # version: v1.104.0

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 1200

      - name: Build image and push to Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.LATEST }}
            ${{ secrets.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:v${{ github.run_number }}
          push: true

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 1200 k8s-1-33-1-do-3-nyc3-telecscope

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/deployment.yml

      - name: Debug Kubernetes Pods
        run: kubectl get pods

      - name: Clear artisan config cache
        run: |
          POD=$(kubectl get pods -o jsonpath='{.items[?(@.status.phase=="Running")].metadata.name}' | grep telescopecm-be || echo "")
          if [ -z "$POD" ]; then
            echo "Error: No running telescopecm-be pod found. Skipping artisan commands."
            exit 1
          fi
          echo "Running php artisan config:clear on pod: $POD"
          for attempt in {1..3}; do
            echo "Config clear attempt $attempt of 3"
            if kubectl exec $POD -- /bin/sh -c "
              set -e
              timeout 300 php artisan config:clear
            "; then
              echo "Config clear successful on attempt $attempt"
              break
            else
              echo "Config clear failed on attempt $attempt. Retrying in 5 seconds..."
              sleep 5
              if [ $attempt -eq 3 ]; then
                echo "Error: All config clear attempts failed."
                exit 1
              fi
            fi
          done

      - name: Run artisan migrate with strict error handling
        run: |
          POD=$(kubectl get pods -o jsonpath='{.items[?(@.status.phase=="Running")].metadata.name}' | grep telescopecm-be || echo "")
          if [ -z "$POD" ]; then
            echo "Error: No running telescopecm-be pod found. Skipping artisan commands."
            exit 1
          fi
          echo "Running php artisan migrate on pod: $POD"
          # Check if tables exist
          TABLE_CHECK=$(kubectl exec $POD -- /bin/sh -c "
            set -e
            php artisan tinker --execute=\"DB::select('SHOW TABLES LIKE ?',['telescope_entries']); DB::select('SHOW TABLES LIKE ?',['telescope_entries_tags']); DB::select('SHOW TABLES LIKE ?',['telescope_monitoring']);\" | grep -c 'telescope'"
          )
          if [ "$TABLE_CHECK" -eq 3 ]; then
            echo "All required telescope tables (telescope_entries, telescope_entries_tags, telescope_monitoring) already exist. Skipping migration."
          else
            for attempt in {1..3}; do
              echo "Migration attempt $attempt of 3"
              if kubectl exec $POD -- /bin/sh -c "
                set -e
                timeout 300 php artisan migrate --force
              "; then
                echo "Migration successful on attempt $attempt"
                break
              else
                echo "Migration failed on attempt $attempt. Retrying in 5 seconds..."
                sleep 5
                if [ $attempt -eq 3 ]; then
                  echo "Error: All migration attempts failed."
                  kubectl exec $POD -- /bin/sh -c "php artisan migrate --force" || true
                  exit 1
                fi
              fi
            done
          fi

      - name: Restart Deployment
        run: kubectl rollout restart deployment telescopecm-be
